name: Build app

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout
        uses: actions/checkout@v4.1.7

      # Step 2: Set up Java JDK
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'adopt'

      # Step 3: Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Step 4: Build APKs for all modules
      - name: Build APKs
        run: ./gradlew :client:assembleDebug :driver:assembleDebug

      # Step 5: Upload artifacts for all modules
      - name: Upload Client APK
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Client-APK
          path: client/build/outputs/apk/debug/client-debug.apk

      - name: Upload Driver APK
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Driver-APK
          path: driver/build/outputs/apk/debug/driver-debug.apk

